services:
  backend:
    ports:
    - "8080:8080"
    image: ulpioro/cloud2-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test
  frontend:
    ports: 
    - "80:80"
    image: ulpioro/cloud2-frontend